# Site settings
title: Jacky's Blog 
email: admin@magicjacky.com
description: > # this means to ignore newlines until "baseurl:"
  假如生活欺骗了你，不要悲伤，不要心急。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magicjacky.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: HelloJacky 

# Build settings
markdown: kramdown

paginate: 4

author: Jacky

gems: [jekyll-paginate]

permalink : /blog/:year/:month/:day/:title
